### ISSUE TITLE
i want to change like TreeCapitator.

### ISSUE THREAD

**Issue by stranger1029** [bspkrs/BlockBreaker#4]
now BlockBreaker is not assign tools.
i hope assign pickaxe and calculate tool damage, applied enchentment effect.

**Comment by bspkrs** [comment]
Just to be clear, you want item damage code like TreeCapitator and enchantment mode?

Not sure what you mean by "i hope assign pickaxe".  Can you explain?

**Comment by portablejim** [comment]
Not exactly sure what he was asking, but it seems to be that.

I would also like this change.

**Comment by bspkrs** [comment]
@portablejim FYI, I am going to start working on BlockBreaker again, so if you have any suggestions as to how things should work (how groups are defined, options for item damage, etc), feel free to open new tickets, submit PRs, or bug me on IRC.  I don't think too many people are using the mod, so any feedback you have is welcome.
