### ISSUE TITLE
TreeCapitator ignores AxeIDList and enchantment settings

### ISSUE THREAD

**Issue by Xalcon** [bspkrs/BlockBreaker#5]
(Well, this was unexpected. Why can i send empty issued? :D)

Anyway:
When enchating Pickaxes with the default config, Pickaxes will get the treecapitating enchantment very often, even when it's disabled by default.

In addition, you may capitate Natura Redwood Trees even when removed from the config.

My Test Setup:
Minecraft 1.5.2 + Forge 7.8.1.738 MCP 7.51
bspkrsCore 2.08
TreeCapitator 1.5.2.r13
nothing else

What I have done:
Place a level 30 Enchantingtable + Books and enchant some diamond pickaxes. 2-4 of 9 get the Treecapitating Enchantment.
The config clearly says _B:enableEnchantmentMode=false_ and _B:requireItemInAxeListForEnchant=true_
The config file does not contain the ID 278 (Diamond Pickaxe)

I've also removed the Natura Redwood Trees from the configuration file on my server - all redwood entries, because you were still able to find a wooden block inside the tree which was capitating the whole tree.. after some minutes of **hacking** :P

**Comment by bspkrs** [comment]
Firstly, this is the wrong repo...

Secondly, if you are not using the latest release, then make sure you are and see if the enchantment crap persists. I'll address the other issues if you end up submitting this to the right repo.
