### ISSUE TITLE
Please update compatibility to 1.7.10

### ISSUE THREAD

**Issue by Andrew900460** [bspkrs/BlockBreaker#6]
I miserably tried to mess with the source code so I could use this mod again in 1.7.10 but it I can't get it to work. Can you update the mod for Minecraft 1.7.10

**Comment by bspkrs** [comment]
No, sorry. VeinMiner is a good replacement for 1.7.10

**Comment by Andrew900460** [comment]
Oh? I had no idea there was a replacement I'll use that one instead. Thanks.
